# Generated by Django 4.1.3 on 2022-12-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
