# Generated by Django 4.1.3 on 2022-12-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_current_bid_alter_listing_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
